apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meu-app
  template:
    metadata:
      labels:
        app: meu-app
    spec:
      containers:
      - name: meu-container
        image: acrcp02.azurecr.io/image-node-jenkins
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: meu-servico
spec:
  selector:
    app: meu-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
